# Generated by Django 5.1 on 2024-09-20 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='فرمت شماره تلفن صحیح نیست', regex='((0?9)|(\\+?989))\\d{2}\\W?\\d{3}\\W?\\d{4}')])),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(choices=[('TourRegistration', 'ثبت نام تور'), ('Suggestions', 'پیشنهادات'), ('Complaints', 'انتقادات')], max_length=200)),
                ('decription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فرم تماس',
                'verbose_name_plural': 'فرم های تماس',
            },
        ),
    ]
