# Generated by Django 5.1 on 2024-10-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0002_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
