# Generated by Django 5.1 on 2024-12-16 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0004_alter_contactform_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='decription',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.CharField(choices=[('TourRegistration', 'ثبت نام تور'), ('Suggestions', 'پیشنهادات'), ('Complaints', 'انتقادات')], max_length=200, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='فرمت شماره تلفن صحیح نیست', regex='((0?9)|(\\+?989))\\d{2}\\W?\\d{3}\\W?\\d{4}')], verbose_name='شماره تلفن'),
        ),
    ]
