# Generated by Django 5.1 on 2024-10-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='logo'),
        ),
    ]
