# Generated by Django 5.1 on 2024-10-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0002_airline_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='flightDuration',
            field=models.DurationField(null=True, verbose_name='مدت زمان سفر رفت'),
        ),
        migrations.AddField(
            model_name='tour',
            name='returnDuraiotn',
            field=models.DurationField(null=True, verbose_name='مدت زمان سفر برگشت'),
        ),
    ]
