# Generated by Django 5.1 on 2024-09-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0002_rename_country_package_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='air_line',
            new_name='airline',
        ),
    ]
