# Generated by Django 5.1 on 2024-10-22 09:02

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0007_tour_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='package',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='price',
            new_name='least_price',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='description',
        ),
        migrations.RemoveField(
            model_name='city',
            name='description',
        ),
        migrations.RemoveField(
            model_name='continent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='country',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='destination_airport',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='origin_airport',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_date',
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', django_jalali.db.models.jDateTimeField()),
                ('arrival', django_jalali.db.models.jDateTimeField()),
                ('return_departure', django_jalali.db.models.jDateTimeField()),
                ('return_arrival', django_jalali.db.models.jDateTimeField()),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('edited_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_airport', to='TourManager.airport')),
                ('origin_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_airport', to='TourManager.airport')),
                ('return_destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_destination_airport', to='TourManager.airport')),
                ('return_origin_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_origin_airport', to='TourManager.airport')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='TourManager.tour')),
            ],
            options={
                'verbose_name': 'رفت و برگشت',
                'verbose_name_plural': 'رفت و برگشت ها',
            },
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
