# Generated by Django 5.1 on 2024-11-03 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0010_tour_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='airline',
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='TourManager.airline'),
            preserve_default=False,
        ),
    ]
