# Generated by Django 5.1 on 2024-11-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0011_remove_tour_airline_flight_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='airport_icons'),
        ),
    ]
