# Generated by Django 5.1 on 2024-11-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0012_airport_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='icon',
        ),
    ]
