# Generated by Django 5.1 on 2024-11-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0013_remove_airport_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='airline_logos/'),
        ),
    ]
