# Generated by Django 5.1 on 2024-11-06 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0014_airline_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_airlines', to='TourManager.airline'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_duration',
            field=models.IntegerField(default=3),
        ),
    ]
