# Generated by Django 5.1 on 2024-11-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0015_alter_flight_airline_alter_tour_tour_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
