# Generated by Django 5.1 on 2024-11-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0017_tour_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/'),
        ),
    ]
