# Generated by Django 5.1 on 2024-12-16 10:09

import django.db.models.deletion
import django_jalali.db.models
import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0018_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_shown',
            field=models.BooleanField(default=True, verbose_name='نمایش داده شود'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='airline_logos/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام هواپیمایی'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airports', to='TourManager.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام فرودگاه'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='short_name',
            field=models.CharField(max_length=10, verbose_name='نام کوتاه'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='TourManager.country', verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام شهر'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام قاره'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='TourManager.continent', verbose_name='قاره'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام کشور'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_airlines', to='TourManager.airline', verbose_name='هواپیمایی'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=django_jalali.db.models.jDateTimeField(verbose_name='زمان فرود رفت'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=django_jalali.db.models.jDateTimeField(verbose_name='زمان پرواز رفت'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_airport', to='TourManager.airport', verbose_name='فرودگاه مقصد'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_airport', to='TourManager.airport', verbose_name='فرودگاه مبدا'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='return_arrival',
            field=django_jalali.db.models.jDateTimeField(verbose_name='زمان فرود برگشت'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='return_departure',
            field=django_jalali.db.models.jDateTimeField(verbose_name='زمان پرواز برگشت'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='return_destination_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_destination_airport', to='TourManager.airport', verbose_name='فرودگاه مقصد برگشت'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='return_origin_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_origin_airport', to='TourManager.airport', verbose_name='فرودگاه مبدا برگشت'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='start_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='شروع قیمت پروازها'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='TourManager.tour', verbose_name='تور'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='agency_service',
            field=models.TextField(verbose_name='خدمات آژانس'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='توضیحات تور'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='TourManager.city', verbose_name='مقصد تور'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='ویژه'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='least_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='کمترین قیمت تور'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='بیشترین قیمت تور'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='needed_documents',
            field=models.TextField(verbose_name='مدارک لازم'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=django_jalali.db.models.jDateField(default=jdatetime.date.today, verbose_name='تاریخ شروع تور'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان تور'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_duration',
            field=models.IntegerField(default=3, verbose_name='مدت زمان تور'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_guide',
            field=models.TextField(verbose_name='راهنمای تور'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('هوایی', 'هوایی'), ('زمینی', 'زمینی')], max_length=200, verbose_name='نوع تور'),
        ),
    ]
