# Generated by Django 5.1.4 on 2024-12-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0019_tour_is_shown_alter_airline_logo_alter_airline_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.AddField(
            model_name='tour',
            name='description_editor',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات تور'),
        ),
    ]
