# Generated by Django 5.1.4 on 2024-12-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0020_remove_tour_description_tour_description_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='occasion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مناسبت'),
        ),
    ]
