# Generated by Django 5.1.4 on 2024-12-18 08:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0021_tour_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description_editor',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
