# Generated by Django 5.1.4 on 2025-01-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0024_remove_tour_destination_tour_destinations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightleg',
            name='duration',
        ),
    ]
