# Generated by Django 5.1.4 on 2025-01-19 12:47

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0026_remove_tour_flightlegs_remove_tour_hotel_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flighttimes',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='flighttimes',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='flighttimes',
            name='arrival_date',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.date.today, verbose_name='تاریخ برگشت'),
        ),
        migrations.AddField(
            model_name='flighttimes',
            name='departure_date',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.date.today, verbose_name='تاریخ رفت'),
        ),
    ]
