# Generated by Django 5.1.4 on 2025-01-19 12:48

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0027_remove_flighttimes_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flighttimes',
            name='arrival_date',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ برگشت'),
        ),
        migrations.AlterField(
            model_name='flighttimes',
            name='departure_date',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ رفت'),
        ),
    ]
