# Generated by Django 5.1.4 on 2025-01-19 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0028_alter_flighttimes_arrival_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='flight_times',
        ),
        migrations.AddField(
            model_name='tour',
            name='flight_times',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_flights', to='TourManager.flighttimes', verbose_name='زمان پرواز'),
        ),
    ]
