# Generated by Django 5.1.4 on 2025-02-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0032_city_is_shown_city_sort_continent_is_shown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightleg',
            name='flight_length',
            field=models.DurationField(blank=True, null=True, verbose_name='مدت پرواز'),
        ),
        migrations.AddField(
            model_name='flightleg',
            name='leg_type',
            field=models.CharField(choices=[('Departure', 'پرواز رفت'), ('ِContinueDeparture', 'ادامه پرواز رفت'), ('Arrival', 'پرواز برگشت'), ('ContinueArrival', 'ادامه پرواز برگشت')], default='Departure', max_length=50, verbose_name='نوع پرواز'),
        ),
        migrations.AddField(
            model_name='flightleg',
            name='stop_time',
            field=models.DurationField(blank=True, null=True, verbose_name='زمان توقف'),
        ),
    ]
