# Generated by Django 5.1 on 2026-10-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0034_tour_least_price_currency_tour_max_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='flight_times',
            field=models.ManyToManyField(blank=True, related_name='tour_flights', to='TourManager.flighttimes', verbose_name='زمان پرواز'),
        ),
    ]
