# Generated by Django 5.1 on 2024-11-06 14:43

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TourManager', '0017_tour_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('edited_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'امکانات هتل',
            },
        ),
        migrations.CreateModel(
            name='RecreationalFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('edited_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'امکانات تفریحی',
            },
        ),
        migrations.CreateModel(
            name='RoomFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('edited_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'امکانات اتاق',
            },
        ),
        migrations.CreateModel(
            name='SportFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('edited_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'امکانات ورزشی',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('star', models.IntegerField(choices=[(1, '1 ستاره'), (2, '2 ستاره'), (3, '3 ستاره'), (4, '4 ستاره'), (5, '5 ستاره'), (6, '6 ستاره')], default=1)),
                ('location_on_map', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('edited_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TourManager.city')),
                ('hotel_facilities', models.ManyToManyField(related_name='hotel_facilities', to='HotelManager.hotelfacilities')),
                ('recreational_facilities', models.ManyToManyField(related_name='recreational_facilities', to='HotelManager.recreationalfacilities')),
                ('room_facilities', models.ManyToManyField(related_name='room_facilities', to='HotelManager.roomfacilities')),
                ('sport_facilities', models.ManyToManyField(related_name='sport_facilities', to='HotelManager.sportfacilities')),
            ],
            options={
                'verbose_name': 'هتل',
                'verbose_name_plural': 'هتل ها',
            },
        ),
        migrations.CreateModel(
            name='HotelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_bed_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('one_bed_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('child_with_bed_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('child_no_bed_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('edited_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_hotels', to='TourManager.flight')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_prices', to='HotelManager.hotel')),
            ],
            options={
                'verbose_name': 'قیمت هتل',
                'verbose_name_plural': 'قیمت های هتل',
            },
        ),
    ]
