# Generated by Django 5.1 on 2024-11-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManager', '0003_alter_hotel_long_description_hotelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimage',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
