# Generated by Django 5.1 on 2024-11-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManager', '0004_hotelimage_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
