# Generated by Django 5.1 on 2024-11-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManager', '0005_hotel_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelfacilities',
            options={'verbose_name': 'امکانات هتل', 'verbose_name_plural': 'امکانات هتل'},
        ),
        migrations.AlterModelOptions(
            name='recreationalfacilities',
            options={'verbose_name': 'امکانات تفریحی', 'verbose_name_plural': 'امکانات تفریحی'},
        ),
        migrations.AlterModelOptions(
            name='roomfacilities',
            options={'verbose_name': 'امکانات اتاق', 'verbose_name_plural': 'امکانات اتاق'},
        ),
        migrations.AlterModelOptions(
            name='sportfacilities',
            options={'verbose_name': 'امکانات ورزشی', 'verbose_name_plural': 'امکانات ورزشی'},
        ),
    ]
