# Generated by Django 5.1 on 2024-12-16 10:09

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManager', '0006_alter_hotelfacilities_options_and_more'),
        ('TourManager', '0019_tour_is_shown_alter_airline_logo_alter_airline_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TourManager.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='edited_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_facilities',
            field=models.ManyToManyField(related_name='hotel_facilities', to='HotelManager.hotelfacilities', verbose_name='امکانات هتل'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='ویژه'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location_on_map',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='موقعیت روی نقشه'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='recreational_facilities',
            field=models.ManyToManyField(related_name='recreational_facilities', to='HotelManager.recreationalfacilities', verbose_name='امکانات تفریحی'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_facilities',
            field=models.ManyToManyField(related_name='room_facilities', to='HotelManager.roomfacilities', verbose_name='امکانات اتاق'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='sport_facilities',
            field=models.ManyToManyField(related_name='sport_facilities', to='HotelManager.sportfacilities', verbose_name='امکانات ورزشی'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star',
            field=models.IntegerField(choices=[(1, '1 ستاره'), (2, '2 ستاره'), (3, '3 ستاره'), (4, '4 ستاره'), (5, '5 ستاره'), (6, '6 ستاره')], default=1, verbose_name='ستاره'),
        ),
        migrations.AlterField(
            model_name='hotelfacilities',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='hotelfacilities',
            name='edited_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='hotelfacilities',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='edited_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='HotelManager.hotel', verbose_name='هتل'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(upload_to='hotel_images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='hotelprice',
            name='child_no_bed_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='قیمت کودک بدون تخت'),
        ),
        migrations.AlterField(
            model_name='hotelprice',
            name='child_with_bed_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='قیمت کودک با تخت'),
        ),
        migrations.AlterField(
            model_name='hotelprice',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='hotelprice',
            name='edited_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='hotelprice',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_hotels', to='TourManager.flight', verbose_name='پرواز'),
        ),
        migrations.AlterField(
            model_name='hotelprice',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_prices', to='HotelManager.hotel', verbose_name='هتل'),
        ),
        migrations.AlterField(
            model_name='hotelprice',
            name='one_bed_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='قیمت یک تخته'),
        ),
        migrations.AlterField(
            model_name='hotelprice',
            name='two_bed_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='قیمت دو تخته'),
        ),
        migrations.AlterField(
            model_name='recreationalfacilities',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='recreationalfacilities',
            name='edited_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='recreationalfacilities',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='roomfacilities',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='roomfacilities',
            name='edited_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='roomfacilities',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='sportfacilities',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='sportfacilities',
            name='edited_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='sportfacilities',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
    ]
