# Generated by Django 5.1.4 on 2024-12-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManager', '0007_alter_hotel_address_alter_hotel_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='star',
            field=models.IntegerField(choices=[(1, '1 ستاره'), (2, '2 ستاره'), (3, '3 ستاره'), (4, '4 ستاره'), (5, '5 ستاره'), (6, '5 ستاره تاپ'), (0, 'هتل آپارتمان')], default=1, verbose_name='ستاره'),
        ),
    ]
