# Generated by Django 5.1.4 on 2025-01-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManager', '0008_alter_hotel_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='english_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام انگلیسی'),
        ),
    ]
