# Generated by Django 5.1.4 on 2025-01-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManager', '0009_hotel_english_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelprice',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='hotelprice',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotelprice',
            name='child_no_bed_price_other_currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='قیمت کودک بدون تخت در ارز دیگر'),
        ),
        migrations.AddField(
            model_name='hotelprice',
            name='child_with_bed_price_other_currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='قیمت کودک با تخت در ارز دیگر'),
        ),
        migrations.AddField(
            model_name='hotelprice',
            name='hotels',
            field=models.ManyToManyField(related_name='hotel_prices', to='HotelManager.hotel', verbose_name='هتل'),
        ),
        migrations.AddField(
            model_name='hotelprice',
            name='one_bed_price_other_currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='قیمت یک تخته در ارز دیگر'),
        ),
        migrations.AddField(
            model_name='hotelprice',
            name='other_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('USD', 'USD')], max_length=10, null=True, verbose_name='ارز دیگر'),
        ),
        migrations.AddField(
            model_name='hotelprice',
            name='two_bed_price_other_currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='قیمت دو تخته در ارز دیگر'),
        ),
    ]
