# Generated by Django 5.1.4 on 2025-01-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManager', '0010_remove_hotelprice_flight_remove_hotelprice_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelprice',
            name='other_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'یورو'), ('USD', 'دلار')], max_length=10, null=True, verbose_name='ارز دیگر'),
        ),
    ]
