# Generated by Django 5.1.4 on 2025-01-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManager', '0011_alter_hotelprice_other_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprice',
            name='baby_price',
            field=models.DecimalField(decimal_places=2, default=2500.0, max_digits=20, verbose_name='قیمت نوزاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelprice',
            name='baby_price_other_currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='قیمت نوزاد در ارز دیگر'),
        ),
    ]
