# Generated by Django 5.1.4 on 2025-02-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManager', '0012_hotelprice_baby_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'هتل', 'verbose_name_plural': '1. هتل ها'},
        ),
        migrations.AlterModelOptions(
            name='hotelfacilities',
            options={'verbose_name': 'امکانات هتل', 'verbose_name_plural': '2. امکانات هتل'},
        ),
        migrations.AlterModelOptions(
            name='recreationalfacilities',
            options={'verbose_name': 'امکانات تفریحی', 'verbose_name_plural': '4. امکانات تفریحی'},
        ),
        migrations.AlterModelOptions(
            name='roomfacilities',
            options={'verbose_name': 'امکانات اتاق', 'verbose_name_plural': '3. امکانات اتاق'},
        ),
        migrations.AlterModelOptions(
            name='sportfacilities',
            options={'verbose_name': 'امکانات ورزشی', 'verbose_name_plural': '5. امکانات ورزشی'},
        ),
    ]
