# Generated by Django 5.1 on 2024-09-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('FaMapLocationDot', 'آیکن نقشه'), ('FaEnvelope', 'آیکن ایمیل'), ('FaPhoneFlip', 'آیکن تلفن'), ('MdAccessTimeFilled', 'آیکن ساعت')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
