# Generated by Django 5.1 on 2024-09-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_contactdetail_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('MdTravelExplore', 'آیکن سفر'), ('FaPlaneDeparture', 'آیکن هواپیما'), ('BiTrip', 'آیکن تور'), ('FaPassport', 'آیکن پاسپورت'), ('BsFillPersonVcardFill', 'آیکن مشتری')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
    ]
