# Generated by Django 5.1 on 2024-11-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_aboutdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdetail',
            name='icon',
            field=models.CharField(choices=[('material-symbols-light:trip', 'آیکن سفر'), ('material-symbols-light:airplane-ticket', 'آیکن هواپیما'), ('material-symbols-light:tour', 'آیکن تور'), ('material-symbols-light:id-card', 'آیکن پاسپورت'), ('material-symbols-light:account-box', 'آیکن مشتری')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='icon',
            field=models.CharField(choices=[('material-symbols-light:location-on-rounded', 'آیکن نقشه'), ('material-symbols-light:mail-rounded', 'آیکن ایمیل'), ('material-symbols-light:phone-enabled', 'آیکن تلفن'), ('material-symbols-light:alarm-rounded', 'آیکن ساعت')], max_length=50),
        ),
    ]
