# Generated by Django 5.1 on 2024-11-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0004_alter_aboutdetail_icon_alter_contactdetail_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('work_time', models.CharField(max_length=200)),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.URLField()),
                ('telegram', models.URLField()),
                ('whatsapp', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.ManyToManyField(to='misc.footerbody')),
            ],
        ),
    ]
