# Generated by Django 5.1 on 2024-11-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0005_footerbody_footercontact_footercolumn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutdetail',
            options={'verbose_name': 'اطلاعات درباره ما', 'verbose_name_plural': 'اطلاعات درباره ما'},
        ),
        migrations.AlterModelOptions(
            name='contactdetail',
            options={'verbose_name': 'اطلاعات تماس با ما', 'verbose_name_plural': 'اطلاعات تماس با ما'},
        ),
        migrations.AlterModelOptions(
            name='footerbody',
            options={'verbose_name': 'بخش داخلی فوتر', 'verbose_name_plural': 'بخش های داخلی فوتر'},
        ),
        migrations.AlterModelOptions(
            name='footercolumn',
            options={'verbose_name': 'ستون فوتر', 'verbose_name_plural': 'ستون های فوتر'},
        ),
        migrations.AlterModelOptions(
            name='footercontact',
            options={'verbose_name': 'اطلاعات تماس فوتر', 'verbose_name_plural': 'اطلاعات تماس فوتر'},
        ),
    ]
