# Generated by Django 5.1 on 2024-12-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0006_alter_aboutdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdetail',
            name='desc',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='aboutdetail',
            name='icon',
            field=models.CharField(choices=[('material-symbols-light:trip', 'آیکن سفر'), ('material-symbols-light:airplane-ticket', 'آیکن هواپیما'), ('material-symbols-light:tour', 'آیکن تور'), ('material-symbols-light:id-card', 'آیکن پاسپورت'), ('material-symbols-light:account-box', 'آیکن مشتری')], max_length=50, verbose_name='آیکن'),
        ),
        migrations.AlterField(
            model_name='aboutdetail',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='desc',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='icon',
            field=models.CharField(choices=[('material-symbols-light:location-on-rounded', 'آیکن نقشه'), ('material-symbols-light:mail-rounded', 'آیکن ایمیل'), ('material-symbols-light:phone-enabled', 'آیکن تلفن'), ('material-symbols-light:alarm-rounded', 'آیکن ساعت')], max_length=50, verbose_name='آیکن'),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='footerbody',
            name='link',
            field=models.CharField(max_length=100, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='footerbody',
            name='title',
            field=models.CharField(max_length=100, verbose_name='متن لینک'),
        ),
        migrations.AlterField(
            model_name='footercolumn',
            name='body',
            field=models.ManyToManyField(to='misc.footerbody', verbose_name='بدنه ستون'),
        ),
        migrations.AlterField(
            model_name='footercolumn',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان ستون'),
        ),
        migrations.AlterField(
            model_name='footercontact',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='footercontact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='footercontact',
            name='instagram',
            field=models.URLField(verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='footercontact',
            name='phone',
            field=models.TextField(verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='footercontact',
            name='telegram',
            field=models.URLField(verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='footercontact',
            name='title',
            field=models.CharField(max_length=100, verbose_name='تیتر اطلاعات تماس فوتر'),
        ),
        migrations.AlterField(
            model_name='footercontact',
            name='whatsapp',
            field=models.URLField(verbose_name='واتساپ'),
        ),
        migrations.AlterField(
            model_name='footercontact',
            name='work_time',
            field=models.CharField(max_length=200, verbose_name='ساعت کاری'),
        ),
    ]
