# Generated by Django 5.1.4 on 2025-02-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0007_alter_aboutdetail_desc_alter_aboutdetail_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerbody',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='footercolumn',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
