# Generated by Django 5.1.4 on 2025-02-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0008_footerbody_sort_footercolumn_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPagePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('pdf', models.FileField(upload_to='main_page_pdfs/', verbose_name='فایل')),
            ],
            options={
                'verbose_name': 'پی دی اف صفحه اصلی',
                'verbose_name_plural': 'پی دی اف های صفحه اصلی',
            },
        ),
    ]
