# Generated by Django 5.1 on 2024-11-13 12:31

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HotelManager', '0005_hotel_is_featured'),
        ('TourManager', '0017_tour_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_bed_quantity', models.IntegerField()),
                ('one_bed_quantity', models.IntegerField()),
                ('child_with_bed_quantity', models.IntegerField()),
                ('child_no_bed_quantity', models.IntegerField()),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('review', 'در انتظار بررسی'), ('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده')], default='review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.flight')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelManager.hotel')),
                ('hotel_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelManager.hotelprice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزرو ها',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persian_name', models.CharField(max_length=100)),
                ('english_name', models.CharField(max_length=100)),
                ('national_code', models.CharField(max_length=10)),
                ('birth_date', django_jalali.db.models.jDateField()),
                ('passport_number', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReserveManager.reserve')),
            ],
        ),
    ]
