# Generated by Django 5.1 on 2024-11-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.CharField(max_length=10),
        ),
    ]
