# Generated by Django 5.1 on 2024-11-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveManager', '0003_reserve_tour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'اطلاعات شخص', 'verbose_name_plural': 'اطلاعات اشخاص'},
        ),
    ]
