# Generated by Django 5.1 on 2024-12-16 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManager', '0007_alter_hotel_address_alter_hotel_city_and_more'),
        ('ReserveManager', '0004_alter_person_options'),
        ('TourManager', '0019_tour_is_shown_alter_airline_logo_alter_airline_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.CharField(max_length=10, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='person',
            name='english_name',
            field=models.CharField(max_length=100, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_code',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='passport_number',
            field=models.CharField(max_length=10, verbose_name='شماره پاسپورت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='persian_name',
            field=models.CharField(max_length=100, verbose_name='نام فارسی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reserve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReserveManager.reserve', verbose_name='رزرو'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='child_no_bed_quantity',
            field=models.IntegerField(verbose_name='تعداد کودک بدون تخت'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='child_with_bed_quantity',
            field=models.IntegerField(verbose_name='تعداد کودک با تخت'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='قیمت نهایی'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.flight', verbose_name='پرواز'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelManager.hotel', verbose_name='هتل'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='hotel_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelManager.hotelprice', verbose_name='قیمت هتل'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='one_bed_quantity',
            field=models.IntegerField(verbose_name='تعداد یک تخته'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='status',
            field=models.CharField(choices=[('review', 'در انتظار بررسی'), ('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده')], default='review', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.tour', verbose_name='تور'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='two_bed_quantity',
            field=models.IntegerField(verbose_name='تعداد دو تخته'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
