# Generated by Django 5.1.4 on 2025-01-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveManager', '0005_alter_person_birth_date_alter_person_english_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='hotel',
        ),
    ]
