# Generated by Django 5.1 on 2024-09-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_category_posts_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Category',
        ),
        migrations.AddField(
            model_name='post',
            name='Category',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.category'),
        ),
    ]
